using System;
using System.Collections.Generic;

namespace testsca.Models
{
    public partial class Ed004pr
    {
        public double Id { get; set; }
        public double? Trkno { get; set; }
        public double? Cusno { get; set; }
        public double? Shpno { get; set; }
        public double? Shpdt { get; set; }
        public double? Prflg { get; set; }
        public double? Daflg { get; set; }
        public double? Ncinv { get; set; }
        public double? Invrf { get; set; }
        public double? Invfl { get; set; }
        public double? Ddflg { get; set; }
        public double? Cmrfl { get; set; }
        public double? Sivfl { get; set; }
        public double? Sddfl { get; set; }
        public double? Issdt { get; set; }
        public double? Invno { get; set; }
        public double? Ddnbr { get; set; }
        public double? Shddt { get; set; }
        public double? Estda { get; set; }
        public double? Estta { get; set; }
        public string? Shpnm { get; set; }
        public string? Shpa1 { get; set; }
        public string? Shpa2 { get; set; }
        public string? Shpa3 { get; set; }
        public string? Shpct { get; set; }
        public string? Shpaa { get; set; }
        public string? Shptp { get; set; }
        public string? Packg { get; set; }
        public double? Carqy { get; set; }
        public double? Palqy { get; set; }
        public double? Gwght { get; set; }
        public double? Nwght { get; set; }
        public string? Wgtum { get; set; }
        public string? Wgtdc { get; set; }
        public double? Volum { get; set; }
        public string? Shpmk { get; set; }
        public string? Unloc { get; set; }
        public string? Carnm { get; set; }
        public string? Cara1 { get; set; }
        public string? Cara2 { get; set; }
        public string? Cara3 { get; set; }
        public string? Sinfo { get; set; }
        public string? Sndnm { get; set; }
        public string? Snda1 { get; set; }
        public string? Snda2 { get; set; }
        public string? Snda3 { get; set; }
        public string? Sndct { get; set; }
        public string? Sndaa { get; set; }
        public double? Bilno { get; set; }
        public string? Bilnm { get; set; }
        public string? Bila1 { get; set; }
        public string? Bila2 { get; set; }
        public string? Bila3 { get; set; }
        public string? Bilct { get; set; }
        public string? Bilaa { get; set; }
        public string? Bilnc { get; set; }
        public string? Bildp { get; set; }
        public string? Biltl { get; set; }
        public string? Bilfx { get; set; }
        public double? Actno { get; set; }
        public string? Actnm { get; set; }
        public string? Acta1 { get; set; }
        public string? Acta2 { get; set; }
        public string? Acta3 { get; set; }
        public string? Actct { get; set; }
        public string? Actaa { get; set; }
        public string? Supcd { get; set; }
        public string? Pytrm { get; set; }
        public double? Frtst { get; set; }
        public string? Trtrm { get; set; }
        public string? Delpt { get; set; }
        public string? Prtrm { get; set; }
        public string? Bnknm { get; set; }
        public string? Bnka1 { get; set; }
        public string? Bnka2 { get; set; }
        public string? Bnka3 { get; set; }
        public string? Bnkno { get; set; }
        public string? Invnc { get; set; }
        public string? Invpt { get; set; }
        public double? Invam { get; set; }
        public string? Curcd { get; set; }
        public string? Curdc { get; set; }
        public double? Taxam { get; set; }
        public double? Taxpc { get; set; }
        public double? Insam { get; set; }
        public double? Frght { get; set; }
        public double? Sblno { get; set; }
        public string? Sblnm { get; set; }
        public string? Sbla1 { get; set; }
        public string? Sbla2 { get; set; }
        public string? Sbla3 { get; set; }
        public string? Sblct { get; set; }
        public string? Sblaa { get; set; }
        public string? Sblnc { get; set; }
        public string? Sbldp { get; set; }
        public string? Sbltl { get; set; }
        public string? Sblfx { get; set; }
        public double? Sacno { get; set; }
        public string? Sacnm { get; set; }
        public string? Saca1 { get; set; }
        public string? Saca2 { get; set; }
        public string? Saca3 { get; set; }
        public string? Sacct { get; set; }
        public string? Sacaa { get; set; }
        public string? Sspcd { get; set; }
        public string? Spytm { get; set; }
        public double? Sfrst { get; set; }
        public string? Strtm { get; set; }
        public string? Sdlpt { get; set; }
        public string? Sprtm { get; set; }
        public string? Sbknm { get; set; }
        public string? Sbka1 { get; set; }
        public string? Sbka2 { get; set; }
        public string? Sbka3 { get; set; }
        public string? Sbkno { get; set; }
        public string? Sinvc { get; set; }
        public string? Sivpt { get; set; }
        public double? Sivam { get; set; }
        public string? Scrcd { get; set; }
        public string? Scrdc { get; set; }
        public double? Stxam { get; set; }
        public double? Stxpc { get; set; }
        public double? Sinam { get; set; }
        public double? Sfrgt { get; set; }
    }
}
